addSbtPlugin("com.geirsson" % "sbt-ci-release" % "1.5.2")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.0.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.1")
addSbtPlugin("com.typesafe" % "sbt-mima-plugin" % "0.6.4")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "2.0.0-RC5-3")
addSbtPlugin("io.get-coursier" % "sbt-shading" % "2.0.0-RC5-3")
